---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-rhel7
  labels:
    app: httpd-rhel7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-rhel7
  template:
    metadata:
      labels:
        app: httpd-rhel7
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpd-rhel7
  name: httpd-rhel7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30036
  selector:
    app: httpd-rhel7
  type: NodePort
status:
  loadBalancer: {}
